// Listes des élèves par classe
// Généré automatiquement depuis les fichiers CSV

const LISTES_ELEVES = {
    "2nde LCQ": [
        { nom: "BODARD--COLAS", prenom: "Lili", sexe: "F" },
        { nom: "BOURRAT", prenom: "Daphné", sexe: "F" },
        { nom: "CHARBONNIER", prenom: "Léna", sexe: "F" },
        { nom: "CHUPIN", prenom: "Coralie", sexe: "F" },
        { nom: "GARNIER", prenom: "Tom", sexe: "M" },
        { nom: "LESIGNE", prenom: "Aaron", sexe: "M" },
        { nom: "MARTY", prenom: "Raphaël", sexe: "M" },
        { nom: "MORAND", prenom: "Manon", sexe: "F" },
        { nom: "VANG", prenom: "Alysson", sexe: "F" },
        { nom: "VINET", prenom: "Romaric", sexe: "M" }
    ],
    "2nde SAPAT AB1": [
        { nom: "AUGEREAU", prenom: "Lily", sexe: "F" },
        { nom: "BADREAU", prenom: "Julia", sexe: "F" },
        { nom: "BERTHAU", prenom: "Anton", sexe: "M" },
        { nom: "BOURDIN", prenom: "Elisa", sexe: "F" },
        { nom: "BOURRIGAUD", prenom: "Naemi", sexe: "F" },
        { nom: "BREMOND", prenom: "Oriane", sexe: "F" },
        { nom: "CRÉPELLIÈRE", prenom: "Jade", sexe: "F" },
        { nom: "DIXNEUF", prenom: "Emy", sexe: "F" },
        { nom: "GUIBAULT", prenom: "Amaya", sexe: "F" },
        { nom: "LEGRAS", prenom: "Ethan", sexe: "M" },
        { nom: "MARTIN", prenom: "Léane", sexe: "F" },
        { nom: "MAUBOUSSIN", prenom: "Bryann", sexe: "M" },
        { nom: "MOREAU", prenom: "Marie", sexe: "F" },
        { nom: "PIARD", prenom: "Ilyana", sexe: "F" },
        { nom: "PINEAU", prenom: "Adrien", sexe: "M" },
        { nom: "ROUSSEAU", prenom: "Ivana", sexe: "F" },
        { nom: "ROY", prenom: "Alexane", sexe: "F" },
        { nom: "SAVARIEAU", prenom: "Maël", sexe: "M" },
        { nom: "SOURISCE", prenom: "Mélyne", sexe: "F" },
        { nom: "THOMAS", prenom: "Noëlie", sexe: "F" },
        { nom: "VAUDELLE--COUËFFÉ", prenom: "Emilio", sexe: "M" },
        { nom: "VEDIE", prenom: "Leelou", sexe: "F" }
    ],
    "2nde SAPAT AB2": [
        { nom: "AUNAI", prenom: "Elian", sexe: "M" },
        { nom: "BODIN", prenom: "Ella", sexe: "F" },
        { nom: "BRIN", prenom: "Loane", sexe: "F" },
        { nom: "CHESSE", prenom: "Morgane", sexe: "F" },
        { nom: "DAUDIN", prenom: "Emmanuelle", sexe: "F" },
        { nom: "DIXNEUF", prenom: "Clément", sexe: "M" },
        { nom: "DURAND", prenom: "Colyne", sexe: "F" },
        { nom: "GOURDON", prenom: "Camille", sexe: "F" },
        { nom: "HODÉ", prenom: "Maëline", sexe: "F" },
        { nom: "LEBRETON", prenom: "Joséphine", sexe: "F" },
        { nom: "LERA", prenom: "Nassira", sexe: "F" },
        { nom: "LORRE", prenom: "Aubin", sexe: "M" },
        { nom: "LUDIER", prenom: "Romane", sexe: "F" },
        { nom: "MARTIN", prenom: "Louise", sexe: "F" },
        { nom: "MENIER", prenom: "Ambre", sexe: "F" },
        { nom: "MONTEIRO", prenom: "Emma", sexe: "F" },
        { nom: "POHARDY", prenom: "Cléo", sexe: "F" },
        { nom: "POIRIER", prenom: "Miléna", sexe: "F" },
        { nom: "POURCHASSE", prenom: "Lionela", sexe: "F" },
        { nom: "ROBERT", prenom: "Océane", sexe: "F" },
        { nom: "SAMI", prenom: "Maëlys", sexe: "F" }
    ],
    "2nde SAPAT AB3": [
        { nom: "AMOURI", prenom: "Manel", sexe: "F" },
        { nom: "BARREAU", prenom: "Noëline", sexe: "F" },
        { nom: "BATARDIÈRE", prenom: "Orane", sexe: "F" },
        { nom: "BAUDON", prenom: "Mélina", sexe: "F" },
        { nom: "BROUARD", prenom: "Nora", sexe: "F" },
        { nom: "BUTET", prenom: "Lauviah", sexe: "F" },
        { nom: "COCHIN", prenom: "Anaïs", sexe: "F" },
        { nom: "COUTOLLEAU", prenom: "Layla", sexe: "F" },
        { nom: "DUPONT", prenom: "Hanaé", sexe: "F" },
        { nom: "FERREIRA", prenom: "RODRIGUES Lorenzo", sexe: "M" },
        { nom: "GADSAUD", prenom: "Nolan", sexe: "M" },
        { nom: "GILLIER", prenom: "Noam", sexe: "M" },
        { nom: "GIRAUD", prenom: "Lilou", sexe: "F" },
        { nom: "GUETTE", prenom: "Bertille", sexe: "F" },
        { nom: "MAHAMAT", prenom: "Hinda", sexe: "F" },
        { nom: "MAILLET", prenom: "Ninon", sexe: "F" },
        { nom: "MARTIN", prenom: "Louna", sexe: "F" },
        { nom: "METIVIER", prenom: "Noa", sexe: "M" },
        { nom: "MOREAU", prenom: "Paulin", sexe: "M" },
        { nom: "MURZEAU", prenom: "Clara", sexe: "F" },
        { nom: "PAPIN", prenom: "Izia", sexe: "F" },
        { nom: "RAPIN", prenom: "Zoé", sexe: "F" }
    ],
    "3e A": [
        { nom: "BONNET", prenom: "Julia", sexe: "F" },
        { nom: "CADIOU", prenom: "Meloée", sexe: "F" },
        { nom: "CHATAIGNER", prenom: "Louis", sexe: "M" },
        { nom: "CLOCHARD", prenom: "Timeo", sexe: "M" },
        { nom: "CORMIER--KHALIFA", prenom: "Anissa", sexe: "F" },
        { nom: "DAMART", prenom: "Gaël", sexe: "M" },
        { nom: "GUERIN", prenom: "Lilou", sexe: "F" },
        { nom: "IMBERT", prenom: "Esteban", sexe: "M" },
        { nom: "JAMARD", prenom: "Malia", sexe: "F" },
        { nom: "LAZAAR", prenom: "Cheryne", sexe: "F" },
        { nom: "LELIEVRE", prenom: "Faustine", sexe: "F" },
        { nom: "MARTIN", prenom: "Marius", sexe: "M" },
        { nom: "MIGEON", prenom: "Benjamin", sexe: "M" },
        { nom: "NERRIERE", prenom: "Adrien", sexe: "M" },
        { nom: "PINEAU", prenom: "Coralie", sexe: "F" },
        { nom: "RENOU", prenom: "Sarah", sexe: "F" },
        { nom: "RIPOCHE", prenom: "Romane", sexe: "F" },
        { nom: "SEDANTON", prenom: "Romane", sexe: "F" },
        { nom: "SUCU", prenom: "Helin", sexe: "F" },
        { nom: "SUPIOT", prenom: "Edwin", sexe: "M" },
        { nom: "YILMAZ", prenom: "Ela", sexe: "F" }
    ],
    "3e B": [
        { nom: "AUGER", prenom: "Faustin", sexe: "M" },
        { nom: "BODY", prenom: "Camélia", sexe: "F" },
        { nom: "BRETHOMÉ", prenom: "Louison", sexe: "M" },
        { nom: "BRISSET--PESTEL", prenom: "Cheyenn", sexe: "F" },
        { nom: "BROCHARD", prenom: "Eden", sexe: "F" },
        { nom: "CAILLAUD", prenom: "Lilou", sexe: "F" },
        { nom: "CAILLAUD", prenom: "Sasha", sexe: "M" },
        { nom: "CHAUVIÈRE--TEIXEIRA", prenom: "Valeska", sexe: "F" },
        { nom: "DELAUNAY", prenom: "Timéo", sexe: "M" },
        { nom: "GAZEAU", prenom: "Alyssa", sexe: "F" },
        { nom: "GODIER", prenom: "Léna", sexe: "F" },
        { nom: "KHEZAZRI", prenom: "Mohamed-Ali", sexe: "M" },
        { nom: "LANZERE-LERICHE", prenom: "Loona", sexe: "F" },
        { nom: "LAVENNE", prenom: "Lily", sexe: "F" },
        { nom: "MONTEIRO", prenom: "Elie", sexe: "F" },
        { nom: "NERRIERE", prenom: "Ely", sexe: "M" },
        { nom: "PIQUET", prenom: "Louis", sexe: "M" },
        { nom: "RAMBEAU", prenom: "Sasha", sexe: "M" },
        { nom: "RONDINEAU", prenom: "Cassandra", sexe: "F" },
        { nom: "SANTI", prenom: "Giosué", sexe: "M" },
        { nom: "TIJOU", prenom: "Zoé", sexe: "F" }
    ],
    "4e": [
        { nom: "ALBERT", prenom: "Baptiste", sexe: "M" },
        { nom: "BERTRAND", prenom: "Eden", sexe: "F" },
        { nom: "BOURASSEAU", prenom: "Chloé", sexe: "F" },
        { nom: "CAMARA", prenom: "Noa", sexe: "M" },
        { nom: "CANO", prenom: "Tylan", sexe: "M" },
        { nom: "CHAMPION", prenom: "Sacha", sexe: "M" },
        { nom: "CHOUTEAU", prenom: "Aubin", sexe: "M" },
        { nom: "DAHMAN", prenom: "Aymen", sexe: "M" },
        { nom: "DURAND", prenom: "Swan", sexe: "M" },
        { nom: "GAIGNIER", prenom: "Ilana", sexe: "F" },
        { nom: "GODINOU", prenom: "Benjamin", sexe: "M" },
        { nom: "GOUGEON", prenom: "Mylann", sexe: "M" },
        { nom: "GUIDA", prenom: "Sami", sexe: "M" },
        { nom: "HAYAULT", prenom: "Timéo", sexe: "M" },
        { nom: "LAURIER", prenom: "Lison", sexe: "F" },
        { nom: "MOREIRA", prenom: "Roméo", sexe: "M" },
        { nom: "MORIN", prenom: "ETRONNIER Dylan", sexe: "M" },
        { nom: "MOUTOUSSAMY", prenom: "Aaron", sexe: "M" },
        { nom: "REMIGEREAU", prenom: "Titouan", sexe: "M" },
        { nom: "SECHET", prenom: "Tibo", sexe: "M" }
    ],
    "Tle SAPAT A": [
        { nom: "AUDIGANE", prenom: "Paoline", sexe: "F" },
        { nom: "BERNARD", prenom: "Hugo", sexe: "M" },
        { nom: "BICHOT", prenom: "Clémence", sexe: "F" },
        { nom: "BRIN", prenom: "Emma", sexe: "F" },
        { nom: "CHEVALIER", prenom: "Apolline", sexe: "F" },
        { nom: "CHOTARD", prenom: "Maëlys", sexe: "F" },
        { nom: "DEFOIS", prenom: "Lounès", sexe: "F" },
        { nom: "FONTENEAU", prenom: "Lilou", sexe: "F" },
        { nom: "FOUCART", prenom: "Liam", sexe: "M" },
        { nom: "GELINEAU", prenom: "Alexis", sexe: "M" },
        { nom: "LAMBERT", prenom: "Ethan", sexe: "M" },
        { nom: "LEMASSON", prenom: "Domitille", sexe: "F" },
        { nom: "MARCHAND", prenom: "Zoé", sexe: "F" },
        { nom: "MESLARD", prenom: "Léonie", sexe: "F" },
        { nom: "MOURET", prenom: "Timéo", sexe: "M" },
        { nom: "POUPARD", prenom: "Camille", sexe: "F" },
        { nom: "PROD'HOMME", prenom: "Loane", sexe: "F" },
        { nom: "RADENAC", prenom: "Manon", sexe: "F" },
        { nom: "REBUFFE", prenom: "Jade", sexe: "F" },
        { nom: "RENAUD", prenom: "Eloïse", sexe: "F" },
        { nom: "RICHARD", prenom: "Iselin", sexe: "M" },
        { nom: "RINEAU", prenom: "Solène", sexe: "F" },
        { nom: "SABOUREAU", prenom: "Thaé", sexe: "M" },
        { nom: "SAULAIS", prenom: "Flavien", sexe: "M" },
        { nom: "SIRE", prenom: "Thaïs", sexe: "F" },
        { nom: "TERRIEN", prenom: "Marine", sexe: "F" }
    ],
    "Tle SAPAT B": [
        { nom: "BARANGER", prenom: "Noéline", sexe: "F" },
        { nom: "BERSON", prenom: "CAILLAUD Manon", sexe: "F" },
        { nom: "BOIDRON", prenom: "Enzo", sexe: "M" },
        { nom: "BROUARD", prenom: "Ilan", sexe: "M" },
        { nom: "CESBRON", prenom: "Manon", sexe: "F" },
        { nom: "CHAILLOU", prenom: "Yoni", sexe: "M" },
        { nom: "CHEVET", prenom: "Yéléna", sexe: "F" },
        { nom: "COME", prenom: "Eléanore", sexe: "F" },
        { nom: "DENION", prenom: "Eloïse", sexe: "F" },
        { nom: "EL", prenom: "MTALSSI Asma", sexe: "F" },
        { nom: "EVON", prenom: "Audrey", sexe: "F" },
        { nom: "FROUIN", prenom: "Emma", sexe: "F" },
        { nom: "GRELET", prenom: "Elise", sexe: "F" },
        { nom: "GRIMAULT", prenom: "Lilou", sexe: "F" },
        { nom: "GUITTIERE", prenom: "Maxence", sexe: "M" },
        { nom: "JOLIVET", prenom: "Kyme", sexe: "F" },
        { nom: "JOUIN", prenom: "Juliette", sexe: "F" },
        { nom: "MARCHAND", prenom: "Sidney", sexe: "F" },
        { nom: "MOREAU", prenom: "Lilie-Jeanne", sexe: "F" },
        { nom: "NORMAND", prenom: "Timéo", sexe: "M" },
        { nom: "PELLETIER", prenom: "Emilien", sexe: "M" },
        { nom: "POINTEAU", prenom: "Leïa", sexe: "F" },
        { nom: "RESNIER", prenom: "Mélissa", sexe: "F" },
        { nom: "TERRIEN", prenom: "Noémie", sexe: "F" },
        { nom: "VIANA", prenom: "Léa", sexe: "F" }
    ]
};

window.__ARCHIVE_LISTES_ELEVES = Object.assign({}, LISTES_ELEVES);
window.getAvailableStudentLists = function () {
    return {};
};
window.getArchiveStudentLists = function () {
    return window.__ARCHIVE_LISTES_ELEVES || {};
};

